packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  core-js: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
